name: Deploy Nginx Config

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure target directory exists
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: sadid
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mkdir -p /opt/infra/nginx
            sudo chown -R sadid:sadid /opt/infra/nginx

      - name: Sync to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: sadid
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/opt/infra/nginx"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: sadid
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo nginx -t && sudo nginx -s reload
